alias: Load Shedding (Stage)
description: ""
trigger:
  - platform: state
    entity_id:
      - sensor.load_shedding_stage_eskom
    attribute: stage
condition:
  - condition: not
    conditions:
      - condition: state
        entity_id: sensor.load_shedding_stage_eskom
        state: unavailable
    alias: Not Unavailable
action:
  - service: notify.mobile_app_all
    data:
      title: Load Shedding
      message: |-
        {% if is_state_attr(trigger.entity_id, "stage", 0) %}
          Suspended
        {% else %}
          {{ states(trigger.entity_id) }}
        {% endif %}
    enabled: true
    alias: Notify
  - choose:
      - conditions:
          - condition: or
            conditions:
              - condition: time
                after: input_datetime.sleep
                weekday:
                  - mon
                  - tue
                  - wed
                  - thu
                  - fri
                  - sat
                  - sun
              - condition: time
                before: input_datetime.wake
                weekday:
                  - sun
                  - sat
                  - fri
                  - thu
                  - wed
                  - tue
                  - mon
        sequence:
          - wait_for_trigger:
              - platform: time
                at: input_datetime.wake
            continue_on_timeout: false
    default: []
    alias: Defer
  - service: tts.home_assistant_say
    data:
      entity_id: media_player.assistant_speakers
      cache: true
      message: |-
        Load Shedding {% if is_state_attr(trigger.entity_id, "stage", 0) %}
          Suspended
        {% else %}
          {{ states(trigger.entity_id) }}
        {% endif %}
    alias: Announce
  - delay:
      hours: 0
      minutes: 0
      seconds: 5
      milliseconds: 0
  - if:
      - condition: state
        entity_id: sensor.load_shedding_area_tshwane_3_garsfonteinext8
        state: "on"
    then:
      - service: tts.home_assistant_say
        data:
          message: Load shedding imminent!
          entity_id: media_player.assistant_speakers
          cache: true
        alias: Announce
    alias: Announce Imminent
mode: restart
