alias: Load Shedding (Warning) (2hr)
description: ""
trigger:
  - platform: numeric_state
    entity_id: sensor.load_shedding_area_tshwane_3_garsfonteinext8
    attribute: starts_in
    below: "120"
condition:
  - condition: and
    conditions:
      - condition:
          - condition: numeric_state
            entity_id: sensor.load_shedding_stage_eskom
            attribute: stage
            above: "0"
        enabled: true
      - condition: time
        after: input_datetime.wake
        before: input_datetime.sleep
action:
  - service: media_player.volume_set
    data:
      volume_level: 0.75
    target:
      entity_id: media_player.assistant_speakers
      device_id: 4b0376fc9b29b09797298badeea28d72
  - service: tts.home_assistant_say
    data:
      entity_id: media_player.assistant_speakers
      message: Load Shedding starts in 2 hours.
      cache: true
mode: single
