alias: Load Shedding (Warning)
description: ""
trigger:
  - platform: numeric_state
    entity_id: sensor.load_shedding_area_eskde_14_milnertoncityofcapetownwesterncape
    attribute: starts_in
    below: "15"
condition:
  - condition: and
    conditions:
      - condition: numeric_state
        entity_id: sensor.load_shedding_stage_eskom
        attribute: stage
        above: "0"
      - condition: time
        after: input_datetime.alarm
        before: input_datetime.sleep
action:
  - service: telegram_bot.send_message
    data:
      message: Load Shedding starts in 15 minutes.
      title: Load Shedding
    enabled: false
  - service: media_player.volume_set
    data:
      volume_level: 0.7
    target:
      entity_id: media_player.assistant_speakers
  - service: tts.home_assistant_say
    data:
      entity_id: media_player.assistant_speakers
      message: Load Shedding starts in 15 minutes.
      cache: true
  - service: rest_command.slack_status
    data:
      emoji: ":gopher-coffee:"
      status: "\"Grabbing coffee before it's too late...\""
    enabled: false
mode: single
